---
title: "**Indiana COVID-19 Tracker**"
author:  "[Eric Book](https://github.com/ercbk)"
output:
  html_document:
    css: style.css
---

----

This website tracks COVID-19 data statewide and by county. Most of the State and County data for positive tests and deaths are gathered from The New York Times COVID-19 [repository](https://github.com/nytimes/covid-19-data) and The Indiana Data [Hub](https://hub.mph.in.gov/dataset).   
  
Governor Holcomb's reopening plan begain on May 12th, 2020. The plan resembles the White House [plan](https://www.whitehouse.gov/openingamerica/) in many aspects, and both are simliar to the [guidelines](https://www.aei.org/research-products/report/national-coronavirus-response-a-road-map-to-reopening/) published by the American Enterpise Institute (AEI) and Johns Hopkins. But neither Governor Holcomb's nor the White House's plan includes the snapback (i.e. reverting to a previous stage) triggering conditions listed in the AEI proposal. Depending on the data that's available, I'll also be trying to track some of the triggers in the AEI proposal and those from Governor Holcomb if any are presented.